// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML;

namespace BlazorServerML.ML
{
    public class Predictor
    {
        public readonly string MODEL_PATH = Startup.PATH + "/ML/HousingPrediction.zip";

        PredictionEngine<HousingData, HousingPrediction> _predictionEngine;

        public Predictor()
        {
            try {
                var mlContext = new MLContext();
                var mlModel = mlContext.Model.Load(MODEL_PATH, out _);
                _predictionEngine = mlContext.Model.CreatePredictionEngine<HousingData, HousingPrediction>(mlModel);

            }
            catch (Exception exception) {
                Console.WriteLine("** Exception: " + exception.Message);
            }
        }

        public HousingPrediction Predict(HousingData input)
        {
            if (_predictionEngine == null) {// unexpected
                return null;
            }
            return _predictionEngine.Predict(input);
        }
    }
}
